estimator:
- name: baseline
  params:
    {}

model:
  dir: "./models/2021-11-23 17-07"
  filepath: "./models/2021-11-23 17-07/model.joblib"

data:
  filepath: "./NewDataset/New_dataset_features.csv"

  
search:
  - estimator: 
    - name: RANSACRegressor
      params: 
        residual_threshold: 20.0
        loss: 'absolute_loss'
  - grid: 
     - max_trials: [40,50,70,80,100,120,150]
       min_samples: [50,100,200,300]

predict:
  filepath: 'something'
  #ruta del modelo
  #dato a predecir

export:
  output_dir: ./models

export_best:
  output_dir: ./grid_models

metrics:
  names:
    - name: custom prediction error
  export:
    filepath: ./metrics.yml
