estimator:
- name: logistic-regressor
  params:
    random_state: 0


data:
  use_new_data: 'si'
  filepath: "./Datasets/Sales_train.csv"
  filepath_new_data: "./NewDataset/New_dataset.csv" 
  process: True


export:
  output_dir: ./models
