Estimator:
- name: RANSACRegressor
  params:
    loss: absolute_loss
    residual_threshold: 20.0
best_params:
  max_trials: 40
  min_samples: 300
best_score: 0.8642272821747514
data:
  filepath: ./NewDataset/New_dataset.csv
grid:
  max_trials:
  - 40
  - 50
  - 70
  - 80
  - 100
  - 120
  - 150
  min_samples:
  - 50
  - 100
  - 200
  - 300
